apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry-proto
  namespace: api
  labels:
    app: telemetry-proto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telemetry-proto
  template:
    metadata:
      labels:
        app: telemetry-proto
    spec:
      restartPolicy: Always
      containers:
      - name: telemetry-proto
        image: <account>.dkr.ecr.<region>.amazonaws.com/proto/telemetry-proto
        ports:
        - containerPort: 8080
        env:
        - name: INFRA
          value: aws-eks/production
        - name: AWS_REGION
          value: us-west-2
        - name: LOKI_ENDPOINT
          value: http://default-opentelemetry-collector.o11y:3500
        - name: OTLP_HTTP_ENDPOINT
          value: http://default-opentelemetry-collector.o11y:4318
        - name: OTLP_ZIPKIN_ENDPOINT
          value: http://default-opentelemetry-collector.o11y:9411
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: telemetry-proto
  name: telemetry-proto
  namespace: api
spec:
  ports:
  - name: 'http'
    port: 8080
    targetPort: 8080
  selector:
    app: telemetry-proto
  type: ClusterIP
