{
 "title": "Logs, Traces, Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "node", "label": "node", "query": "label_values(k8s_node_name)" },
   { "name": "pod", "label": "pod", "query": "label_values(k8s_pod_name)" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(k8s_namespace_name)"
   },
   { "name": "trace_id", "label": "trace_id", "query": "label_values(trace_id)" }
  ]
 },
 "panels": [
  {
   "title": "Logs for applicaiton pod",
   "type": "logs",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{k8s_node_name=~\"$node\", k8s_pod_name=~\"$pod\", k8s_namespace_name=~\"$namespace\", trace_id=~\"$trace_id\"}"
    }
   ]
  },
  {
   "title": "Trace View for trace with id $trace_id",
   "type": "traces",
   "gridPos": { "h": 15, "w": 23, "x": 0, "y": 10 },
   "targets": [
    { "query": "$trace_id" }
   ]
  },
  {
   "title": "latency for All",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(1.00, sum(rate(http_server_requests_seconds_bucket{uri=~\".*\"}[$__rate_interval])) by (le))",
     "legendFormat": "max"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{uri=~\".*\"}[$__rate_interval])) by (le))",
     "legendFormat": "tp99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{uri=~\".*\"}[$__rate_interval])) by (le))",
     "legendFormat": "tp95"
    }
   ]
  }
 ]
}